name: Create React App in Root

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-react-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean root (optional)
        run: |
          find . -mindepth 1 \
            ! -path "./.git*" \
            ! -path "./.github*" \
            -exec rm -rf {} +

      - name: Create React App in Repository Root
        run: |
          npm create vite@latest . -- --template react
          npm install

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Initialize React Vite app in repository root" || echo "Nothing to commit"
          git push
